version = "1.0"

[main]
name = "Dotclear2 configuration"

    [main.super_user]
    name = "Main permission for YunoHost users"

        [main.super_user.admin]
        ask = "Super Administrator"
        type = "user"
        bind = "super_user:__INSTALL_DIR__/inc/class.auth.ldap.php"

    [main.php_fpm_config]
        name = "PHP-FPM configuration"

        [main.php_fpm_config.fpm_footprint]
        ask = "Memory footprint"
        type = "select"
        choices.low = "Low, <= 20Mb per pool"
        choices.medium = "Medium, between 20Mb and 40Mb per pool"
        choices.high = "High, > 40Mb per pool"
        choices.specific = "Use specific value"
        default = "low"

        [main.php_fpm_config.fpm_free_footprint]
        visible = "fpm_footprint == 'specific'"
        ask = "Memory footprint of the service?"
        type = "number"
        default = "0"
        help = "Free field to specify exactly the footprint in Mb if you don't want to use one of the three previous values."

        [main.php_fpm_config.fpm_usage]
        ask = "Expected usage"
        type = "select"
        choices = ["low", "medium", "high"]
        default = "low"
        help = "low: Personal usage, behind the SSO. No RAM footprint when not used, but the impact on the processor can be high if many users are using the service.<br>medium: Low usage, few people or/and publicly accessible. Low RAM footprint, medium processor footprint when used.<br>high: High usage, frequently visited website. High RAM footprint, but lower on processor usage and quickly responding."

[ynh_users]
name = "Yunohost users"
help = "These permissions apply to the first connection of the user, the super user can change them in dotclear."

    [ynh_users.main_permission]
    name = "Permissions for YunoHost users"

        [ynh_users.main_permission.blog_admin]
        ask = "Administrator"
        type = "boolean"
        yes = "true"
        no = "false"
        bind = "'admin':__INSTALL_DIR__/inc/class.auth.ldap.php"

        [ynh_users.content]
        name = "Content permissions"
        visible = "blog_admin != 'true'"
            
            [ynh_users.content.blog_contentadmin]
            ask = "Manage all entries and comments"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'contentadmin':__INSTALL_DIR__/inc/class.auth.ldap.php"

            [ynh_users.content.blog_usage]
            ask = "Manage their own entries and comments"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'usage':__INSTALL_DIR__/inc/class.auth.ldap.php"
            visible = "blog_contentadmin != 'true'"

            [ynh_users.content.blog_publish]
            ask = "Publish entries and comments"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'publish':__INSTALL_DIR__/inc/class.auth.ldap.php"
            visible = "blog_contentadmin != 'true'"

            [ynh_users.content.blog_delete]
            ask = "Delete entries and comments"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'delete':__INSTALL_DIR__/inc/class.auth.ldap.php"
            visible = "blog_contentadmin != 'true'"

        [ynh_users.media]
        name = "Media permissions"
        visible = "blog_admin != 'true'"

            [ynh_users.media.blog_media_admin]
            ask = "Manage all media items"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'media_admin':__INSTALL_DIR__/inc/class.auth.ldap.php"

            [ynh_users.media.blog_media]
            ask = "Manage their own media items"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'media':__INSTALL_DIR__/inc/class.auth.ldap.php"
            visible = "blog_media_admin != 'true'"

        [ynh_users.other_permissions]
        name = "Other permissions"
        visible = "blog_admin != 'true'"

            [ynh_users.other_permissions.blog_categories]
            ask = "Manage categories"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'categories':__INSTALL_DIR__/inc/class.auth.ldap.php"

            [ynh_users.other_permissions.blog_pages]
            ask = "Manage pages"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'pages':__INSTALL_DIR__/inc/class.auth.ldap.php"

            [ynh_users.other_permissions.blog_blogroll]
            ask = "Manage blogroll"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'blogroll':__INSTALL_DIR__/inc/class.auth.ldap.php"
