version = "1.0"

[main]
name = "Dotclear2 configuration"

    [main.super_user]
    name = "Main permission for YunoHost users"

        [main.super_user.admin]
        ask = "Super Administrator"
        type = "user"
        bind = "super_user:__INSTALL_DIR__/inc/class.auth.ldap.php"

[ynh_users]
name = "Yunohost users"
help = "These permissions apply to the first connection of the user, the super user can change them in dotclear."

    [ynh_users.main_permission]
    name = "Permissions for YunoHost users"

        [ynh_users.main_permission.blog_admin]
        ask = "Administrator"
        type = "boolean"
        yes = "true"
        no = "false"
        bind = "'admin':__INSTALL_DIR__/inc/class.auth.ldap.php"

        [ynh_users.content]
        name = "Content permissions"
        visible = "blog_admin != 'true'"
            
            [ynh_users.content.blog_contentadmin]
            ask = "Manage all entries and comments"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'contentadmin':__INSTALL_DIR__/inc/class.auth.ldap.php"

            [ynh_users.content.blog_usage]
            ask = "Manage their own entries and comments"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'usage':__INSTALL_DIR__/inc/class.auth.ldap.php"
            visible = "blog_contentadmin != 'true'"

            [ynh_users.content.blog_publish]
            ask = "Publish entries and comments"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'publish':__INSTALL_DIR__/inc/class.auth.ldap.php"
            visible = "blog_contentadmin != 'true'"

            [ynh_users.content.blog_delete]
            ask = "Delete entries and comments"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'delete':__INSTALL_DIR__/inc/class.auth.ldap.php"
            visible = "blog_contentadmin != 'true'"

        [ynh_users.media]
        name = "Media permissions"
        visible = "blog_admin != 'true'"

            [ynh_users.media.blog_media_admin]
            ask = "Manage all media items"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'media_admin':__INSTALL_DIR__/inc/class.auth.ldap.php"

            [ynh_users.media.blog_media]
            ask = "Manage their own media items"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'media':__INSTALL_DIR__/inc/class.auth.ldap.php"
            visible = "blog_media_admin != 'true'"

        [ynh_users.other_permissions]
        name = "Other permissions"
        visible = "blog_admin != 'true'"

            [ynh_users.other_permissions.blog_categories]
            ask = "Manage categories"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'categories':__INSTALL_DIR__/inc/class.auth.ldap.php"

            [ynh_users.other_permissions.blog_pages]
            ask = "Manage pages"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'pages':__INSTALL_DIR__/inc/class.auth.ldap.php"

            [ynh_users.other_permissions.blog_blogroll]
            ask = "Manage blogroll"
            type = "boolean"
            yes = "true"
            no = "false"
            bind = "'blogroll':__INSTALL_DIR__/inc/class.auth.ldap.php"

[blogs]
name = "Multiple blogs management"
help = "Here you can instruct YunoHost to handle multiple blogs. It will create the appropriate permissions and NGINX configuration files. You still need to add them in Dotclear's administration panel. Removing them here will not delete them from Dotclear, and vice-versa."

    [blogs.blogs_list]
    name = "List of blogs to handle"

        [blogs.blogs_list.blogs_list]
        ask = "List blogs with the format `id@domain.example/path`"
        type = "tags"
        pattern.regexp = "[\\w]+@[\\w.]+\\/[\\w]*"
        pattern.error = "Incorrect format. Use `id@domain.example/path`"
