#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.init_admin_permission="package_checker"

    test_upgrade_from.bca9fa0e72faf78e020e0483f76b89c28c7620cf.name = "2.27.3~ynh1"
    test_upgrade_from.bca9fa0e72faf78e020e0483f76b89c28c7620cf.args.domain="domain.tld"
    test_upgrade_from.bca9fa0e72faf78e020e0483f76b89c28c7620cf.args.path="/dotclear2"
    test_upgrade_from.bca9fa0e72faf78e020e0483f76b89c28c7620cf.args.admin="package_checker"
    test_upgrade_from.bca9fa0e72faf78e020e0483f76b89c28c7620cf.args.is_public="true"
