#!/bin/bash
# DotClear 2 backup script for YunoHost

app=dotclear2

# The parameter $1 is the backup directory location
# which will be compressed afterward
backup_dir=$1/apps/$app
sudo mkdir -p $backup_dir

# Backup sources
sudo cp -a /var/www/$app/. $backup_dir/sources

# Backup database
db_password=$(sudo yunohost app setting $app db_password)
sudo mysqldump -u $app -p"$db_password" $app > $backup_dir/dump.sql

# Copy Nginx and YunoHost parameters to make the script "standalone"
sudo cp -a /etc/yunohost/apps/$app/. $backup_dir/yunohost
domain=$(sudo yunohost app setting $app domain)
sudo cp -a /etc/nginx/conf.d/$domain.d/$app.conf $backup_dir/nginx.conf

