#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================
set__blogs_list() {

    declare -A domain_array
    declare -A path_array

    for blog in $(echo $blogs_list | sed "s/,/ /"); do
        id=$(echo $blog | cut -d@ -f1)
        domain=$(echo $blog | cut -d@ -f2 | cut -d/ -f1)
        path="/$(echo $blog | cut -d@ -f2 | cut -d/ -f2)"

        domain_array+=([$id]=$domain)
        path_array+=([$id]=$path)
    done

    declare -A old_domain_array
    declare -A old_path_array

    for blog in $(echo ${old[blogs_list]} | sed "s/,/ /"); do
        id=$(echo $blog | cut -d@ -f1)
        domain=$(echo $blog | cut -d@ -f2 | cut -d/ -f1)
        path="/$(echo $blog | cut -d@ -f2 | cut -d/ -f2)"

        old_domain_array+=([$id]=$domain)
        old_path_array+=([$id]=$path)
    done

    # https://stackoverflow.com/questions/2312762/compare-difference-of-two-arrays-in-bash
    # Get added and removed blogs
    added_ids_array=(`echo ${!domain_array[@]} ${!old_domain_array[@]} | tr ' ' '\n' | sort | uniq -u `)
    removed_ids_array=(`echo ${!old_domain_array[@]} $!domain_array[@]} | tr ' ' '\n' | sort | uniq -D | uniq `)

    for id in $removed_ids_array; do
        if [ ynh_permission_exists --permission="$id" ]; then
            ynh_permission_delete --permission="$id"
        fi
        ynh_secure_remove --file="/etc/nginx/conf.d/${old_domain_array[$id]}.d/$app.conf"
    done

    for id in $domain_array; do
    
        if [ $domain_array[$id] != $old_domain_array[$id] ]; then
            mv /etc/nginx/conf.d/${old_domain_array[$id]}.d/$app.conf /etc/nginx/conf.d/${domain_array[$id]}.d/$app.conf
        fi
        
        if [ $path_array[$id] != $old_path_array[$id] ]; then
            domain=$domain_array[$id]
            path=$path_array[$id]
            ynh_add_config --template="nginx.conf" --destination="/etc/nginx/conf.d/${domain_array[$id]}.d/$app.conf"
        fi

        if [ ynh_permission_exists --permission="$id" ]; then
            ynh_permission_url --permission="$id" --url="$domain_array[$id]$path_array[$id]"
            ynh_permission_url --permission="$id.admin" --url="$domain_array[$id]$path_array[$id]/admin"
        else
            ynh_permission_create --permission="$id" --url="$domain_array[$id]$path_array[$id]"
            ynh_permission_create --permission="$id.admin" --url="$domain_array[$id]$path_array[$id]/admin"
        fi
        
    done
    
    ynh_app_setting_set $app blogs_list $blogs_list
}
