#!/bin/bash
# DotClear 2 installation script for YunoHost

app=dotclear2_test2
domain=$1
path=$2

# Check domain/path availability asap
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    echo "This $domain$path is already in use, installation canceled"
    exit 1
fi

admin=$3
admin_password=$4
is_public=$5
directory=/var/www/$app
php_config=$directory/inc/config.php
master_key=`dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p'`
firstname=`sudo yunohost user info $admin | grep firstname: | cut -d' ' -f2 | tr -d '\n'`
lastname=`sudo yunohost user info $admin | grep lastname: | cut -d' ' -f2 | tr -d '\n'`
email=`sudo yunohost user info $admin | grep mail: | cut -d' ' -f2 | tr -d '\n'`
TZ=`cat /etc/timezone | tr -d '\n'`

# Save app settings
sudo yunohost app setting $app admin -v "$admin"
sudo yunohost app setting $app admin_password -v "$admin_password"
sudo yunohost app setting $app is_public -v "$is_public"


# Make sure we got the tools we need for this install
sudo apt-get install -y curl wget sed

# Initialize database and store mysql password for upgrade
db_password=`sudo yunohost app initdb $app | tr -d '\n'`
sudo yunohost app setting $app mysqlpwd -v $db_password

# Get sources
cd /tmp
sudo wget http://download.dotclear.org/latest.tar.gz -O $app.tgz
sudo tar xf $app.tgz
sudo mv dotclear $directory
sudo rm -f $app.tgz
cd $directory
sudo cp $php_config.in $php_config
sudo chown www-data:www-data -R $app

# Config as if we called in admin/install/wizard.php
sudo sed -i -e "s;'DC_DBDRIVER','';'DC_DBDRIVER','mysqli';" -e "s;'DC_DBHOST','';'DC_DBHOST','localhost';" -e "s;'DC_DBUSER','';'DC_DBUSER','$app';" -e "s;'DC_DBPASSWORD','';'DC_DBPASSWORD','$db_password';" -e "s;'DC_DBNAME','';'DC_DBNAME','$app';" -e "s;'DC_MASTER_KEY','';'DC_MASTER_KEY','$master_key';" -e "s;'DC_ADMIN_URL','';'DC_ADMIN_URL','https://$domain$path/admin/index.php';" -e "s;'DC_ADMIN_MAILFROM','';'DC_ADMIN_MAILFROM','$email';" $php_config

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$directory/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is public, add url to SSOWat conf as skipped_uris
if [ "$is_public" = "Yes" ];
then
  # unprotected_uris allows SSO credentials to be passed anyway.
  sudo yunohost app setting $app unprotected_uris -v "/"
fi

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf

# Setting first user details and filling database calling admin/install/index.php
success=`curl -F "u_email=$EMAIL" -F "u_firstname=$FIRSTNAME" -F "u_name=$NAME" -F "u_login=$LOGIN" -F "u_pwd=$admin_password" -F "u_pwd2=$admin_password" -F "u_date=$TZ" https://$domain$path/admin/install/index.php`

# Success or not success
if [ `echo $success | grep -c success` -gt 0 ]
then
    echo Installation OK, $app should be available here https://$domain$path/
    exit 0
else
    echo Using curl to finish setup failed, open https://$domain$path/admin/install/index.php and do it yourself 
    exit 10
fi

