#!/bin/bash
# DotClear 2 restore script for YunoHost

app=dotclear2

# The parameter $1 is the uncompressed restore directory location
backup_dir=$1/apps/$app

# Restore sources
sudo cp -a $backup_dir/sources/. /var/www/$app

# Restore database
root_pwd=$(sudo cat /etc/yunohost/mysql)
mysql -u root -p$root_pwd -e "DROP DATABASE $app ; DROP USER $app@localhost ;"
db_password=$(sudo yunohost app setting $app db_password)
sudo yunohost app initdb $app -p "$db_password" -s $backup_dir/dump.sql

# Restore Nginx and YunoHost parameters
sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app
domain=$(sudo yunohost app setting $app domain)
sudo cp -a $backup_dir/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Restart webserver
sudo service nginx reload
