#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if [ -z "${blog_admin:-}" ] ||
 [ -z "$blog_contentadmin" ] ||
 [ -z "$blog_usage" ] ||
 [ -z "$blog_publish" ] ||
 [ -z "$blog_delete" ] ||
 [ -z "$blog_categories" ] ||
 [ -z "$blog_media_admin" ] ||
 [ -z "$blog_media" ] ||
 [ -z "$blog_pages" ] ||
 [ -z "$blog_blogroll" ]; then
	blog_admin="false"
	blog_contentadmin="false"
	blog_usage="true"
	blog_publish="false"
	blog_delete="false"
	blog_categories="false"
	blog_media_admin="false"
	blog_media="false"
	blog_pages="false"
	blog_blogroll="false"
 	ynh_app_setting_set --key=blog_admin --value=$blog_admin
 	ynh_app_setting_set --key=blog_contentadmin --value=$blog_contentadmin
	ynh_app_setting_set --key=blog_usage --value=$blog_usage
	ynh_app_setting_set --key=blog_publish --value=$blog_publish
	ynh_app_setting_set --key=blog_delete --value=$blog_delete
	ynh_app_setting_set --key=blog_categories --value=$blog_categories
 	ynh_app_setting_set --key=blog_media_admin --value=$blog_media_admin
	ynh_app_setting_set --key=blog_media --value=$blog_media
	ynh_app_setting_set --key=blog_pages --value=$blog_pages
	ynh_app_setting_set --key=blog_blogroll --value=$blog_blogroll
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

_dotclear2_setup_source


chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

# https://dotclear.org/documentation/2.0/admin/install
mkdir -p "$install_dir/"{cache,public}
setfacl -m d:u:www-data:rwx "$install_dir/"{cache,public}

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

php_config=$install_dir/inc/config.php

ynh_backup_if_checksum_is_different $php_config

cp $php_config.in $php_config

admin_url="${path%/}/admin/"

email=$(ynh_user_get_info --username=$admin --key=mail)

# Config as if we called in admin/install/wizard.php
ynh_replace --match="'DC_DBDRIVER', ''" --replace="'DC_DBDRIVER', 'mysqli'" --file=$php_config
ynh_replace --match="'DC_DBHOST', ''" --replace="'DC_DBHOST', 'localhost'" --file=$php_config
ynh_replace --match="'DC_DBUSER', ''" --replace="'DC_DBUSER', '$db_user'" --file=$php_config
ynh_replace --match="'DC_DBPASSWORD', ''" --replace="'DC_DBPASSWORD', '$db_pwd'" --file=$php_config
ynh_replace --match="'DC_DBNAME', ''" --replace="'DC_DBNAME', '$db_name'" --file=$php_config
ynh_replace --match="'DC_MASTER_KEY', ''" --replace="'DC_MASTER_KEY', '$master_key'" --file=$php_config
ynh_replace --match="'DC_ADMIN_URL', ''" --replace="'DC_ADMIN_URL', 'https://$domain$admin_url'" --file=$php_config
ynh_replace --match="'DC_ADMIN_MAILFROM', ''" --replace="'DC_ADMIN_MAILFROM', '$email'" --file=$php_config
ynh_replace --match="//define('DC_NOT_UPDATE', false);" --replace="define('DC_NOT_UPDATE', true);" --file=$php_config

# Adding LDAP login
ynh_config_add --template="class.auth.ldap.php" --destination="$install_dir/inc/class.auth.ldap.php"

cat << EOF >> $php_config

require dirname(__FILE__).'/class.auth.ldap.php';
define('DC_AUTH_CLASS','ldapDcAuth');
EOF

# Recalculate and store the checksum of the file for the next upgrade.
ynh_store_file_checksum $php_config

chmod 400 "$php_config"
chown $app:$app "$php_config"

#=================================================
# UPDATING DATABASE
#=================================================

# Navigate to the admin panel to upgrade the database: https://dotclear.org/documentation/2.0/admin/upgrades
adminUrl="/admin/auth.php"
ynh_local_curl $adminUrl

#=================================================
# UPGRADE FAIL2BAN
#=================================================
ynh_script_progression "Reconfiguring Fail2Ban..."

ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Invalid credentials in $install_dir/inc/class.auth.ldap.php .* client: <HOST>, .*https://$domain${path%/}/admin/auth.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
